name: Lunatalk-Backend

on:
  push:
    branches: [ develop ]

jobs:
  continuous-integration:
    name: Laravel Workflows
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, mysql, libxml, xml, xmlwriter, dom, tokenizer, filter, json, phar, pcre, openssl, pdo, intl, curl

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Prepare the application
        run: |
          php -r "copy('.env.github', '.env');"
          php artisan key:generate
      - name: Clear Config
        run: php artisan config:clear

      - name: Test with phpunit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit --coverage-text

      - name: deploy to development server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOPMENT_SERVER_IP }}
          username: ${{ secrets.DEVELOPMENT_SERVER_USER_NAME}}
          key: ${{ secrets.DEVELOPMENT_SSH_PRIVATE_KEY }}
          script:
            cd /var/www/site/lunatalk.co.kr/dev.service && ./deploy.sh
